apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: healpolicy-validator
webhooks:
  - name: validate.healpolicy.healmesh.io
    rules:
      - apiGroups: ["healmesh.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["healpolicies"]
        scope: "Namespaced"
    clientConfig:
      service:
        name: healmesh-executor
        namespace: healmesh
        path: "/validate-healpolicy"
      caBundle: "Cg==" # Will be injected by cert-manager or manual in practice
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Fail
