apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: healpolicy-validator
webhooks:
  - name: validate.healpolicy.healmesh.io
    rules:
      - apiGroups: ["healmesh.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["healpolicies"]
        scope: "Namespaced"
    clientConfig:
      url: "https://host.docker.internal:8443/validate-healpolicy"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lVTnVMVlVkc3JCNVYrMVorWW84R0E5ZHFnYytNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0h6RWRNQnNHQTFVRUF3d1VhRzl6ZEM1a2IyTnJaWEl1YVc1MFpYSnVZV3d3SGhjTk1qWXdOekUwTVRrdwpPVEl6V2hjTk1qY3dOekUwTVRrd09USXpXakFmTVIwd0d3WURWUVFEREJSb2IzTjBMbVJ2WTJ0bGNpNXBiblJsCmNtNWhiRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFQTGV4UDFseUdUY28xY1IKUUNUUU82WCtnZHcwRmt4VUZFcGFsb2JTeVQwSzNXTGM4Q2FNaVFqWHVlVkk1YUVNL0VGa3pjNnpTZGNnWFZkUAp5TUlRaEFXckZ1K0FJdHVTdm83czhMV0pja01ESUs5aTVoTlVCMytOdW8yKzF4U2RxNVZudXRTbUFuQk9XZDFDCkdIdmxUWmVybFN6RUVaUzljdEEyM0ZvbTFXZHIzVGovQTljVnFOaU1zUFRyVlcvN2xwRHJ0elowRmJkcmZnaDcKY01lMWd5Snd2cUhZV24wZEFLRkJCYkxwRE9tekh2M0ppMFRUQXBxNUhLcThCanYxVm1iUmlENTBiZXdZby9wNgpjbFR3MnVQM1dZWEpUTmFMVlhqYUlZZXBJbk1kdkFEcXJ5NmRzSFMwS3YwRC81Qk5zUUk0OFIrQnQ3bGQ2ZDJ5Cnc4eDlMak1DQXdFQUFhTjBNSEl3SFFZRFZSME9CQllFRkFiZ1pFKzFnZFBlV20vSTJRc1p6WThzaHd4S01COEcKQTFVZEl3UVlNQmFBRkFiZ1pFKzFnZFBlV20vSTJRc1p6WThzaHd4S01BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpId1lEVlIwUkJCZ3dGb0lVYUc5emRDNWtiMk5yWlhJdWFXNTBaWEp1WVd3d0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSitHa3NOTjFkRmpka2tjUDljMUtaZ0w1VEZGWU5Kajh0eFpXd3BrYUlKL0VvS1JkbXltVFN0MWlianEKdWloQi9RdVpoWGV1ak85VHJmVi9aTndHQU02enpYN0V1cytIZXNSL2NvcUlEM0dtWlI5ZXFQYUQyQWhGYy9lYgo1WHJKeXBGY0dMWC9OYm9rRGpxODlIbllJZkdNUmlHakI2WDZnRHc1c0xtQzJCZ2JCQzdvTWNaNWRzeDRBZU9vCnRxWk92cmhoU0NObHFWa3ZTTEtGYUM2bWRaVDBGeDl3dit5a28xaFovYnYvRW9iVDNPSEZhbm9jVlpxMWlneEsKbU41WlVLQmk1UU81RHB1cWpwY1liVXZtUGdjU3M5b0YySHBmbGFsRzd5dEo3Z3U2Qyt4MEhmakNibTJLNW56UgpPZE0wOEhHSWlUaDFCMGNQVDdSeElkc055Umc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Fail
